name: Shadowfall Workshop
favicon: null
layout_spectrum: 0.42640517745167017
typography_spectrum: 0.001879341434687376
title: Shadowfall Workshop
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9565834277309477
  lightness: 0.020463979803025723
  saturation: 0.19368732394650578
  rhythmicContrast: 0.0526108609046787
purpose: []
